### ISSUE TITLE
Kernel configuration is invalid

### ISSUE THREAD

**Issue by T-Hollenbeck** [emmercm/rpi-rtl8812au#2]
pi@raspberrypi:~ $ ./rpi-rtl8812au 
./rpi-rtl8812au: Zeile 1: !/usr/bin/env: Datei oder Verzeichnis nicht gefunden
Checking online version ...
   4.2.2

Checking for installed driver ...
   Did not find any driers

Checking rtl8812au HEAD version ...
   978c1f628ffb13b359f7266287364da8aeacec36

Cloning from git to /sr/src/rtl8812au-978c1f6 ...
Running make ...

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

make[1]: *** [Makefile:704: include/config/auto.conf] Fehler 1
make: *** [Makefile:1077: modules] Fehler 2

**Comment by emmercm** [comment]
Would you be able to provide the Raspberry Pi model number, distro, and kernel information? I can try to reproduce on my end and see if there's a problem with newer driver versions or newer hardware/kernel versions.
